import { CarType, type Car } from '../types';

// Deterministic image URLs based on ID to ensure they stay the same
export const AVAILABLE_CARS: Car[] = [
    {
        id: 'c1',
        make: 'Tesla',
        model: 'Model Y Performance',
        year: 2024,
        price: 54000,
        type: CarType.ELECTRIC,
        color: 'Midnight Silver',
        mileage: 1500,
        description: 'A versatile electric SUV with incredible acceleration and autopilot capabilities. Perfect for tech-savvy families.',
        features: ['Autopilot', 'Heated Seats', 'Glass Roof', '0-60 in 3.5s'],
        imageUrl: 'https://picsum.photos/id/111/800/600'
    },
    {
        id: 'c2',
        make: 'Porsche',
        model: '911 Carrera',
        year: 2022,
        price: 115000,
        type: CarType.SPORTS,
        color: 'Guards Red',
        mileage: 8500,
        description: 'The quintessential sports car. Timeless design meets modern performance engineering.',
        features: ['Sport Chrono', 'Leather Interior', 'Bose Sound', '379 HP'],
        imageUrl: 'https://picsum.photos/id/133/800/600'
    },
    {
        id: 'c3',
        make: 'Toyota',
        model: 'RAV4 Hybrid',
        year: 2023,
        price: 32000,
        type: CarType.SUV,
        color: 'Magnetic Gray',
        mileage: 12000,
        description: 'Reliable, fuel-efficient, and spacious. The ultimate practical choice for daily driving.',
        features: ['AWD', 'Apple CarPlay', 'Safety Sense 2.5', '40 MPG'],
        imageUrl: 'https://picsum.photos/id/183/800/600'
    },
    {
        id: 'c4',
        make: 'Ford',
        model: 'F-150 Lariat',
        year: 2023,
        price: 62000,
        type: CarType.TRUCK,
        color: 'Antimatter Blue',
        mileage: 5000,
        description: 'Built Ford Tough. A luxury workhorse capable of towing heavy loads while keeping you comfortable.',
        features: ['4x4', 'Leather Seats', 'Tow Package', 'Pro Power Onboard'],
        imageUrl: 'https://picsum.photos/id/146/800/600'
    },
    {
        id: 'c5',
        make: 'Mercedes-Benz',
        model: 'S-Class S500',
        year: 2021,
        price: 98000,
        type: CarType.SEDAN,
        color: 'Obsidian Black',
        mileage: 18000,
        description: 'The benchmark for luxury sedans. Offers a ride so smooth you will forget you are moving.',
        features: ['Massage Seats', 'Burmester 3D Sound', 'Augmented Reality HUD', 'Ambient Lighting'],
        imageUrl: 'https://picsum.photos/id/107/800/600'
    },
    {
        id: 'c6',
        make: 'Rivian',
        model: 'R1T',
        year: 2023,
        price: 78000,
        type: CarType.ELECTRIC,
        color: 'Rivian Blue',
        mileage: 3000,
        description: 'The electric adventure truck. Go anywhere, do anything, with zero emissions.',
        features: ['Quad-Motor', 'Gear Tunnel', 'Air Suspension', 'Camping Kitchen Ready'],
        imageUrl: 'https://picsum.photos/id/296/800/600'
    },
    {
        id: 'c7',
        make: 'BMW',
        model: 'M3 Competition',
        year: 2024,
        price: 85000,
        type: CarType.SPORTS,
        color: 'Isle of Man Green',
        mileage: 1200,
        description: 'A high-performance sedan that delivers adrenaline-pumping speed with everyday usability.',
        features: ['503 HP', 'Carbon Bucket Seats', 'Drift Analyzer', 'Harman Kardon Sound'],
        imageUrl: 'https://picsum.photos/id/10/800/600'
    },
    {
        id: 'c8',
        make: 'Hyundai',
        model: 'Ioniq 5',
        year: 2023,
        price: 45000,
        type: CarType.ELECTRIC,
        color: 'Cyber Gray',
        mileage: 5000,
        description: 'Retro-futuristic styling meets cutting-edge EV technology. Fast charging and spacious interior.',
        features: ['800V Charging', 'V2L Adapter', 'Relaxation Seats', 'Pixel Lights'],
        imageUrl: 'https://picsum.photos/id/13/800/600'
    },
    {
        id: 'c9',
        make: 'Jeep',
        model: 'Wrangler Rubicon',
        year: 2022,
        price: 52000,
        type: CarType.SUV,
        color: 'Firecracker Red',
        mileage: 15000,
        description: 'The ultimate off-road icon. Removable doors and roof for an immersive nature experience.',
        features: ['33-inch Tires', 'Locking Differentials', 'Sway Bar Disconnect', 'Waterproof Interior'],
        imageUrl: 'https://picsum.photos/id/14/800/600'
    },
    {
        id: 'c10',
        make: 'Audi',
        model: 'RS6 Avant',
        year: 2024,
        price: 125000,
        type: CarType.SPORTS,
        color: 'Nardo Gray',
        mileage: 2500,
        description: 'The super-wagon that can carry the whole family at supercar speeds.',
        features: ['591 HP', 'Quattro AWD', 'Air Suspension', 'Bang & Olufsen 3D Sound'],
        imageUrl: 'https://picsum.photos/id/15/800/600'
    },
    {
        id: 'c11',
        make: 'Chevrolet',
        model: 'Corvette Stingray',
        year: 2023,
        price: 72000,
        type: CarType.SPORTS,
        color: 'Rapid Blue',
        mileage: 4000,
        description: 'Mid-engine American exotic performance at an unbeatable price point.',
        features: ['V8 Engine', 'Removable Top', 'Z51 Package', 'GT2 Seats'],
        imageUrl: 'https://picsum.photos/id/16/800/600'
    },
    {
        id: 'c12',
        make: 'Lexus',
        model: 'RX 350',
        year: 2023,
        price: 58000,
        type: CarType.SUV,
        color: 'Eminent White Pearl',
        mileage: 8000,
        description: 'Comfort and reliability wrapped in a stylish luxury SUV package.',
        features: ['Mark Levinson Audio', 'Panoramic Roof', 'Safety System+ 3.0', 'Ventilated Seats'],
        imageUrl: 'https://picsum.photos/id/17/800/600'
    },
    {
        id: 'c13',
        make: 'Mazda',
        model: 'MX-5 Miata',
        year: 2022,
        price: 32000,
        type: CarType.SPORTS,
        color: 'Soul Red Crystal',
        mileage: 10000,
        description: 'Pure driving joy. Lightweight, responsive, and incredibly fun on winding roads.',
        features: ['Manual Transmission', 'Bilstein Shocks', 'Brembo Brakes', 'Recaro Seats'],
        imageUrl: 'https://picsum.photos/id/18/800/600'
    },
    {
        id: 'c14',
        make: 'Volvo',
        model: 'XC90 Recharge',
        year: 2024,
        price: 75000,
        type: CarType.SUV,
        color: 'Crystal White',
        mileage: 1000,
        description: 'Scandinavian luxury with plug-in hybrid efficiency and top-tier safety.',
        features: ['7 Seats', 'Pilot Assist', 'Orrefors Crystal Shifter', 'Google Built-in'],
        imageUrl: 'https://picsum.photos/id/19/800/600'
    },
    {
        id: 'c15',
        make: 'Subaru',
        model: 'Outback Wilderness',
        year: 2023,
        price: 42000,
        type: CarType.SUV,
        color: 'Geyser Blue',
        mileage: 12000,
        description: 'Rugged capability for the adventurous family. Higher ground clearance and all-terrain tires.',
        features: ['Symmetrical AWD', 'X-MODE', 'StarTex Upholstery', 'Roof Rails'],
        imageUrl: 'https://picsum.photos/id/20/800/600'
    },
    {
        id: 'c16',
        make: 'Honda',
        model: 'Civic Type R',
        year: 2023,
        price: 48000,
        type: CarType.SPORTS,
        color: 'Championship White',
        mileage: 3500,
        description: 'The ultimate hot hatch. Track-ready performance with daily driver practicality.',
        features: ['315 HP', '6-Speed Manual', 'Active Exhaust', 'LogR Data Logger'],
        imageUrl: 'https://picsum.photos/id/21/800/600'
    },
    {
        id: 'c17',
        make: 'Lucid',
        model: 'Air Touring',
        year: 2024,
        price: 105000,
        type: CarType.ELECTRIC,
        color: 'Zenith Red',
        mileage: 500,
        description: 'Luxury electric sedan with class-leading range and breathtaking performance.',
        features: ['425 Mile Range', 'Glass Canopy', 'DreamDrive Pro', 'Surreal Sound'],
        imageUrl: 'https://picsum.photos/id/22/800/600'
    },
    {
        id: 'c18',
        make: 'GMC',
        model: 'Sierra 1500 Denali',
        year: 2023,
        price: 75000,
        type: CarType.TRUCK,
        color: 'White Frost Tricoat',
        mileage: 9000,
        description: 'Professional grade capability meets first-class luxury.',
        features: ['Super Cruise', 'MultiPro Tailgate', 'CarbonPro Bed', 'Head-Up Display'],
        imageUrl: 'https://picsum.photos/id/23/800/600'
    },
    {
        id: 'c19',
        make: 'Kia',
        model: 'Telluride SX-Prestige',
        year: 2024,
        price: 53000,
        type: CarType.SUV,
        color: 'Wolf Gray',
        mileage: 2000,
        description: 'Award-winning 3-row SUV that punches well above its weight class in luxury and features.',
        features: ['Nappa Leather', 'Dual Sunroofs', 'Blind-Spot View Monitor', 'Digital Key'],
        imageUrl: 'https://picsum.photos/id/24/800/600'
    },
    {
        id: 'c20',
        make: 'Volkswagen',
        model: 'Golf GTI',
        year: 2022,
        price: 35000,
        type: CarType.SPORTS,
        color: 'Kings Red Metallic',
        mileage: 18000,
        description: 'The original hot hatch. Fun to drive, practical, and solidly built.',
        features: ['Plaid Seats', 'DSG Transmission', 'IQ.DRIVE', 'Ambient Lighting'],
        imageUrl: 'https://picsum.photos/id/25/800/600'
    },
    {
        id: 'c21',
        make: 'Land Rover',
        model: 'Defender 110',
        year: 2023,
        price: 82000,
        type: CarType.SUV,
        color: 'Pangea Green',
        mileage: 7500,
        description: 'Modern interpretation of a legend. Unstoppable off-road, refined on-road.',
        features: ['Air Suspension', 'ClearSight Mirror', 'Meridian Sound', 'Terrain Response 2'],
        imageUrl: 'https://picsum.photos/id/26/800/600'
    },
    {
        id: 'c22',
        make: 'Genesis',
        model: 'GV80',
        year: 2023,
        price: 68000,
        type: CarType.SUV,
        color: 'Cardiff Green',
        mileage: 11000,
        description: 'Distinctive design and opulent luxury from the rising Korean premium brand.',
        features: ['3D Instrument Cluster', 'Remote Smart Parking', 'Lexicon Audio', 'Ergo Motion Seat'],
        imageUrl: 'https://picsum.photos/id/27/800/600'
    },
    {
        id: 'c23',
        make: 'Nissan',
        model: 'Z Performance',
        year: 2023,
        price: 52000,
        type: CarType.SPORTS,
        color: 'Ikazuchi Yellow',
        mileage: 4500,
        description: 'A tribute to Z history with modern twin-turbo power.',
        features: ['400 HP', 'Mechanical LSD', 'Launch Control', 'SynchroRev Match'],
        imageUrl: 'https://picsum.photos/id/28/800/600'
    },
    {
        id: 'c24',
        make: 'Cadillac',
        model: 'Escalade ESV',
        year: 2022,
        price: 110000,
        type: CarType.SUV,
        color: 'Black Raven',
        mileage: 22000,
        description: 'The king of American luxury SUVs. Massive presence and massive space.',
        features: ['OLED Curved Display', 'Super Cruise', 'AKG Studio Reference', 'Console Fridge'],
        imageUrl: 'https://picsum.photos/id/29/800/600'
    },
    {
        id: 'c25',
        make: 'Polestar',
        model: '2',
        year: 2023,
        price: 55000,
        type: CarType.ELECTRIC,
        color: 'Magnesium',
        mileage: 6000,
        description: 'Minimalist Scandinavian design in a high-performance electric fastback.',
        features: ['Ohlins Dampers', 'Brembo Brakes', 'Android Automotive', 'Pixel LED Headlights'],
        imageUrl: 'https://picsum.photos/id/30/800/600'
    },
    {
        id: 'c26',
        make: 'Toyota',
        model: 'GR Supra',
        year: 2023,
        price: 58000,
        type: CarType.SPORTS,
        color: 'Stratosphere Blue',
        mileage: 5500,
        description: 'A pure sports car developed on the track. Sharp handling and a powerful inline-six.',
        features: ['382 HP', 'Adaptive Suspension', 'Active Differential', 'JBL Audio'],
        imageUrl: 'https://picsum.photos/id/31/800/600'
    },
    {
        id: 'c27',
        make: 'Ram',
        model: '1500 TRX',
        year: 2022,
        price: 95000,
        type: CarType.TRUCK,
        color: 'Ignition Orange',
        mileage: 14000,
        description: 'The apex predator of trucks. Supercharged V8 power for desert running.',
        features: ['702 HP', 'Bilstein Black Hawk Shocks', 'Launch Control', 'Head-Up Display'],
        imageUrl: 'https://picsum.photos/id/32/800/600'
    },
    {
        id: 'c28',
        make: 'Mini',
        model: 'Cooper SE',
        year: 2024,
        price: 34000,
        type: CarType.ELECTRIC,
        color: 'British Racing Green',
        mileage: 2000,
        description: 'The iconic go-kart feeling, now electric. Perfect for city zipping.',
        features: ['Iconic Trim', 'Union Jack Taillights', 'Head-Up Display', 'Harman Kardon'],
        imageUrl: 'https://picsum.photos/id/33/800/600'
    },
    {
        id: 'c29',
        make: 'Alfa Romeo',
        model: 'Giulia Quadrifoglio',
        year: 2021,
        price: 78000,
        type: CarType.SEDAN,
        color: 'Rosso Etna',
        mileage: 19000,
        description: 'Italian passion on four wheels. One of the best driving sedans ever made.',
        features: ['Ferrari-derived V6', 'Carbon Fiber Hood', 'Active Aero', 'DNA Pro Drive Modes'],
        imageUrl: 'https://picsum.photos/id/34/800/600'
    },
    {
        id: 'c30',
        make: 'Jaguar',
        model: 'F-Type R',
        year: 2023,
        price: 108000,
        type: CarType.SPORTS,
        color: 'Firenze Red',
        mileage: 4000,
        description: 'Stunningly beautiful and brutally fast. The sound of the V8 is addictive.',
        features: ['575 HP', 'AWD', 'Switchable Active Exhaust', 'Windsor Leather Performance Seats'],
        imageUrl: 'https://picsum.photos/id/35/800/600'
    },
    {
        id: 'c31',
        make: 'Acura',
        model: 'Integra Type S',
        year: 2024,
        price: 52000,
        type: CarType.SPORTS,
        color: 'Tiger Eye Pearl',
        mileage: 1500,
        description: 'Premium performance liftback. Engaging to drive with a touch of luxury.',
        features: ['320 HP', '6-Speed Manual', 'ELS Studio 3D Audio', 'Head-Up Display'],
        imageUrl: 'https://picsum.photos/id/36/800/600'
    }
];